# Generated by Django 4.2.30 on 2026-07-31 06:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_add_is_visible_to_projectphoto'),
        ('clients', '0003_client_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, help_text='Scope of works / project description')),
                ('terms', models.TextField(blank=True, help_text='Contract terms and conditions')),
                ('contract_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Deposit required as % of contract amount', max_digits=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Signed', 'Signed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('client_signature_name', models.CharField(blank=True, help_text='Name of the person signing on behalf of the client', max_length=200)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='projects.project')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
