# Generated by Django 4.2.30 on 2026-07-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='owner_signature_name',
            field=models.CharField(blank=True, help_text='Name of the company authorised signatory', max_length=200),
        ),
        migrations.AddField(
            model_name='contract',
            name='owner_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
