# Generated by Django 4.2.30 on 2026-08-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_owner_signature_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='client_signature_data',
            field=models.TextField(blank=True, help_text='Handwritten signature image (data URI)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='owner_signature_data',
            field=models.TextField(blank=True, help_text='Handwritten signature image (data URI)'),
        ),
    ]
