# Generated by Django 5.2.3 on 2026-06-17 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role__in': ('site_supervisor', 'store_keeper', 'employee')}, on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
