# Generated by Django 4.2.30 on 2026-07-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectassignment_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectphoto',
            options={'ordering': ['-is_cover', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='Show this photo as the project cover on the portfolio'),
        ),
    ]
