# Generated by Django 4.2.30 on 2026-07-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_is_cover_to_projectphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectphoto',
            options={'ordering': ['-is_cover', 'sort_order', 'uploaded_at']},
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower = first, after cover)'),
        ),
    ]
