# Generated by Django 4.2.30 on 2026-07-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_sort_order_to_projectphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphoto',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of this photo (e.g. what stage of construction)'),
        ),
    ]
