# Generated by Django 4.2.30 on 2026-07-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_description_to_projectphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphoto',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show this photo on the public portfolio page'),
        ),
    ]
