# Generated by Django 5.2.3 on 2026-06-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('project_manager', 'Project Manager'), ('accountant', 'Accountant'), ('site_supervisor', 'Site Supervisor'), ('store_keeper', 'Store Keeper'), ('employee', 'Employee'), ('client', 'Client')], default='employee', max_length=20),
        ),
    ]
