# Generated by Django 5.2.3 on 2026-06-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='tawk_to_property_id',
            field=models.CharField(blank=True, help_text='Tawk.to Property ID (e.g. 123abc)', max_length=50),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='tawk_to_widget_id',
            field=models.CharField(blank=True, help_text='Tawk.to Widget ID (e.g. 1a2b3c4d5)', max_length=50),
        ),
    ]
