# Generated by Django 4.2.30 on 2026-07-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projecthouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthouse',
            name='image',
            field=models.CharField(help_text='Image filename in static/project-houses/ (e.g. project-house-1.jpg)', max_length=200),
        ),
    ]
