# Generated by Django 4.2.30 on 2026-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_contact_submission_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthouse',
            name='image',
            field=models.ImageField(upload_to='project-houses/'),
        ),
    ]
