# Generated by Django 4.2.30 on 2026-07-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_revert_projecthouse_image_to_imagefield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecthouse',
            options={'ordering': ['title', 'order', '-created_at'], 'verbose_name': 'Project House', 'verbose_name_plural': 'Project Houses'},
        ),
    ]
