# Generated by Django 4.2.30 on 2026-07-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_revert_projecthouse_image_to_imagefield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecthouse',
            options={'ordering': ['category', 'order', '-created_at'], 'verbose_name': 'Project House', 'verbose_name_plural': 'Project Houses'},
        ),
        migrations.AddField(
            model_name='projecthouse',
            name='category',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Mixed Use', 'Mixed Use'), ('Institutional', 'Institutional'), ('Industrial', 'Industrial'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
