# Generated by Django 4.2.30 on 2026-07-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fix_projecthouse_ordering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectHouse',
        ),
    ]
