# Generated by Django 4.2.30 on 2026-08-25 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_add_is_visible_to_projectphoto'),
        ('documents', '0002_document_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('letter', 'Letter'), ('report', 'Report')], default='letter', max_length=10)),
                ('reference_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, help_text='Rich-text HTML content')),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('recipient_organization', models.CharField(blank=True, max_length=200)),
                ('recipient_address', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=200)),
                ('report_period', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('show_signature', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
