# Generated by Django 5.2.3 on 2026-06-16 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('category', models.CharField(choices=[('cement', 'Cement'), ('sand', 'Sand'), ('gravel', 'Gravel'), ('steel', 'Steel'), ('paint', 'Paint'), ('timber', 'Timber'), ('other', 'Other')], max_length=20, verbose_name='Category')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('bags', 'Bags'), ('pieces', 'Pieces'), ('litres', 'Litres'), ('m3', 'm³')], max_length=10, verbose_name='Unit')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Cost')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Supplier')),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Reorder Level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=3, verbose_name='Type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Done By')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='inventory.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
