# Generated by Django 5.2.3 on 2026-06-16 15:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Employee ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('position', models.CharField(choices=[('project_manager', 'Project Manager'), ('site_supervisor', 'Site Supervisor'), ('foreman', 'Foreman'), ('mason', 'Mason'), ('carpenter', 'Carpenter'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('welder', 'Welder'), ('painter', 'Painter'), ('driver', 'Driver'), ('laborer', 'Laborer'), ('security', 'Security'), ('cleaner', 'Cleaner'), ('accountant', 'Accountant'), ('admin', 'Admin'), ('other', 'Other')], max_length=30, verbose_name='Position')),
                ('department', models.CharField(choices=[('management', 'Management'), ('finance', 'Finance'), ('construction', 'Construction'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('painting', 'Painting'), ('transport', 'Transport'), ('security', 'Security'), ('other', 'Other')], max_length=30, verbose_name='Department')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salary')),
                ('employment_date', models.DateField(verbose_name='Employment Date')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, verbose_name='Emergency Phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Note')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_notes', to='employees.employee', verbose_name='Employee')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_performance', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
            ],
            options={
                'verbose_name': 'Performance Note',
                'verbose_name_plural': 'Performance Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Check In')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Check Out')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half-Day')], default='present', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'employee__user__first_name'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
